# Build stage
FROM golang:1.24.2-alpine as builder

WORKDIR /app
COPY . .

RUN go mod tidy
RUN go build -o main .

# Run stage
FROM alpine:latest

WORKDIR /root/
COPY --from=builder /app/main .

RUN apk add --no-cache ca-certificates

CMD ["./main"]
