name: Go CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go 1.24.2
        uses: actions/setup-go@v2
        with:
          go-version: "1.24.2"

      - name: Install dependencies
        run: go mod tidy

      - name: Build the Go app
        run: go build -o main .

      - name: Run tests
        run: go test ./...
