name: Fullstack Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---- BACKEND ----
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"

      - name: Build Go backend
        working-directory: backend
        run: |
          go mod tidy
          go build -v ./...

      - name: Run Go backend (test run briefly)
        working-directory: backend
        run: |
          timeout 5s go run main.go || true
        # timeout 5s artinya jalan 5 detik, lalu berhenti
        # || true supaya meskipun timeout, tetap success

      # ---- FRONTEND ----
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # atau versi Node.js yang sesuai project kamu

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build Svelte frontend
        working-directory: frontend
        run: npm run build
